language: php

matrix:
  include:
  - php: 7.1
    env: ILLUMINATE_MINOR_VERSION=6
  - php: 7.2
    env: ILLUMINATE_MINOR_VERSION=6
  - php: 7.1
    env: ILLUMINATE_MINOR_VERSION=7
  - php: 7.2
    env: ILLUMINATE_MINOR_VERSION=7

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - composer require "laravel/framework:5.${ILLUMINATE_MINOR_VERSION}.*" --no-update
  - composer require "orchestra/testbench:3.${ILLUMINATE_MINOR_VERSION}.*" --no-update

install:
  - travis_retry composer update --prefer-source --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
